### ISSUE TITLE
Wondering what the ban/kick reason was, or if its even a valid one

### ISSUE THREAD

**Issue by WHITED4WN** [Nyanotrasen/Nyanotrasen#1232]
## Description
Discord doesnt show ban/kick reasons.

**Reproduction**
Ban/kick someone, server simply disappears from the server list.

**Additional context**
I think Rane might be letting their personal vendetta get ahead of actual moderation.

**Comment by Elijahrane** [comment]
3 out of the 4 top heads were in favor of rule 0ing you. Do not open another issue.
